---
name: Run E2E tests on new code in master
'on':
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          DEBUG: '@cypress/github-action'
        with:
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:4321'
          wait-on-timeout: 360

      - name: Upload E2E run data as artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-run-data
          path: |
            /home/runner/work/forgingmodernity.com/forgingmodernity.com/cypress/screenshots/*
            /home/runner/work/forgingmodernity.com/forgingmodernity.com/cypress/videos/*
          retention-days: 14
